version: 2.1
orbs:
  codecov: codecov/codecov@5.3.0
jobs:
  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: img-processing-api-v1-
      - run: npm install
      - save_cache:
          key: img-processing-api-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npx prettier --check .
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: sudo apt-get update
      - restore_cache:
          key: img-processing-api-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: img-processing-api-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run coverage
      - codecov/upload

workflows:
  run-testing:
    jobs:
      - lint
      - test
